### PR TITLE
Completed Refactor of WorkerLoad

### PR DESCRIPTION
**Pull request by felix2feng**

### CODE REVIEW

**Comment by anhtaiH** [comment]
One note:

In ActionsModel.js, the responseTime should be changed to elapseTime per our discussion last week. The changes in the main repo is about to be updated with my most recent pull request as well.

Can you change this

**Comment by felix2feng** [comment]
Yup, good catch. just to be clear. It's 'elapsedTime' - rather than elapseTime right?

**Comment by anhtaiH** [comment]
Correct

**Comment by anhtaiH** [comment]
One more thing, config.example.env has a duplicate JWT_SECRET. Can you remove that as well? I am updating this file in the main repo too.

**Comment by felix2feng** [comment]
Done

**Pull request merged**
